kind: pipeline
type: docker
name: default

steps:
- name: update-from-master
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: dev_host
    user: 
      from_secret: dev_ssh_user
    key:
      from_secret: dev_ssh_key
    port: 22
    command_timeout: 1m
    script:
      - echo "Hello World"

trigger:
  branch:
  - add-drone-for-cd
  event:
  - push